apiVersion: apps/v1
kind: Deployment
metadata:
  name: taxi-trip-consumer

spec:
  replicas: 1

  selector:
    matchLabels:
      app: taxi-trip-consumer

  template:
    metadata:
      labels:
        app: taxi-trip-consumer
      annotations:
        prometheus.io/port: "80"
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: taxi-trip-consumer
          image: gcr.io/distributed-systems-279515/taxi-trip-consumer:1
          env:
            - name: MONGODB_ATLAS_CONNECTION_STRING
              value: "mongodb://mongoadmin:123456@mongo-db-mongodb.default.svc.cluster.local:27017/profits"