apiVersion: apps/v1
kind: Deployment
metadata:
  name: taxi-trip-consumer

spec:
  replicas: 1

  selector:
    matchLabels:
      app: taxi-trip-consumer

  template:
    metadata:
      labels:
        app: taxi-trip-consumer
      annotations:
        prometheus.io/port: "80"
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: taxi-trip-consumer
          image: gcr.io/distributed-systems-279515/taxi-trip-consumer:1
          env:
            - name: MONGODB_ATLAS_CONNECTION_STRING
              value: "mongodb+srv://mongoadmin:D3YIzSqm87QD6so4@abs-mongo-cluster-oalh6.azure.mongodb.net/admin?retryWrites=true&w=majority"