apiVersion: apps/v1
kind: Deployment
metadata:
  name: taxi-trip-consumer

spec:
  replicas: 1

  selector:
    matchLabels:
      app: taxi-trip-consumer

  template:
    metadata:
      labels:
        app: taxi-trip-consumer
    spec:
      containers:
        - name: taxi-trip-consumer
          image: gcr.io/distributed-systems-279515/taxi-trip-consumer:1