apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregated-visualisations

spec:
  replicas: 4

  selector:
    matchLabels:
      deploy: aggregated-visualisations

  template:
    metadata:
      labels:
        deploy: aggregated-visualisations
    spec:
      containers:
        - name: aggregated-visualisations
          image: gcr.io/distributed-systems-279515/aggregated-visualisations:1
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGODB_ATLAS_CONNECTION_STRING
              value: "mongodb://mongoadmin:123456@mongo-db-mongodb.default.svc.cluster.local:27017/profits"
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 1Gi
